version: '3.8'

services:
  ros:
    build:
      context: .
      dockerfile: docker/Dockerfile

    network_mode: host

    # ============================================================
    # GPU SUPPORT (Gazebo / RViz)
    # ============================================================
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    environment:
      # NVIDIA GPU
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

      # GUI (RViz / Gazebo)
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=xcb
      - XAUTHORITY=/root/.Xauthority

      # Gazebo model/resource path for local models in the mounted workspace
      - GAZEBO_MODEL_PATH=/ros2_ws/src/my_robot_description/worlds/sample_blender:${GAZEBO_MODEL_PATH}
      - GZ_SIM_RESOURCE_PATH=/ros2_ws/src/my_robot_description/worlds/sample_blender:${GZ_SIM_RESOURCE_PATH}

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /dev/bus/usb:/dev/bus/usb:rw
      
      # DYNAMIC HARDWARE FIX: Bind-mount the entire inputs folder
      - /dev/input:/dev/input:rw
      
      # Your ROS workspace
      - /home/dinesh/ros_basics:/ros2_ws

      # SLAM toolbox config
      - /opt/ros/jazzy/share/slam_toolbox/config/:/opt/ros/jazzy/share/slam_toolbox/config/

    # ============================================================
    # DEVICE ACCESS (IMPORTANT FIX)
    # ============================================================
    devices:
      - /dev/dri:/dev/dri
      - /dev/input:/dev/input
      - /dev/bus/usb:/dev/bus/usb

    privileged: true

    tty: true
    stdin_open: true