model {
  file: "model.sdf"
}
name: "Spectrum_Wall_Mount"
description: "Spectrum Wall Mount"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Spectrum"
}
annotations {
  key: "gtin"
  value: "00010591602002"
}
annotations {
  key: "sku"
  value: "00010591602002"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Consumer Goods"
}
