controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController


diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.5
    wheel_radius: 0.1

    base_frame_id: "base_link"
    odom_frame_id: "odom"

    enable_odom_tf: true
    publish_rate: 50

    linear.x:
      has_velocity_limits: 222
      max_velocity: 1.0
      min_velocity: -1.0
      has_acceleration_limits: true
      max_acceleration: 2.0
      min_acceleration: -2.0

    angular.z:
      has_velocity_limits: true
      max_velocity: 1.0
      min_velocity: -1.0
      has_acceleration_limits: true
      max_acceleration: 2.0
      min_acceleration: -2.0