controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController


joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true


diff_drive_controller:
  ros__parameters:

    left_wheel_names: ["base_to_left_wheel"]
    right_wheel_names: ["base_to_right_wheel"]

    wheel_separation: 0.45
    wheel_radius: 0.1

    odom_frame_id: "odom"
    base_frame_id: "base_footprint_link"

    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    